on:
  # Trigger analysis when pushing in "main" branch. Change this to another branch if you need to
  push:
    branches:
      - main
name: TMScanner Workflow
jobs:
  tmscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: TMScanner Scan
      uses: htpata/tmscanner-github-action@main
      with:
        tm_url: http://129.148.26.53:6862
        tm_repository_id: 342
        tm_file: hello.sol      
      env:
        # All parameters are required
        # TM_URL: URL of the TMScanner system assigned to you by the TMScanner team (in this example: http://129.148.26.53:6862)
        # TM_REPOSITORY_ID: Use an already existing repository id in the TMScanner system (in this example: 120)
        # TM_SOURCE: The .sol file (or .zip with many .sol files inside) that you want to analyze (in this example: hello.sol)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TM_TOKEN: ${{ secrets.TM_TOKEN }}
       